import Foundation

nonisolated enum GentleReminders {
    static let all: [String] = [
        "Your progress is waiting for you.",
        "Stay on track today.",
        "You're building momentum.",
        "Quick check-in available.",
        "One tap to keep your streak going.",
        "You're doing great — check in today.",
        "A moment for yourself today.",
        "Small steps lead to big changes.",
        "You've come further than you think.",
        "Today is another chance to show up.",
        "You're stronger than yesterday.",
        "Keep going — you're worth it.",
        "Consistency is your superpower.",
        "One day at a time.",
        "You're proving something to yourself.",
        "This is what progress looks like.",
        "Check in and keep the chain going.",
        "Your future self will thank you.",
        "You're already doing the hard part.",
        "Another day, another win.",
        "Stay steady. You've got this.",
        "Progress doesn't need to be perfect.",
        "You showed up yesterday. Show up today.",
        "Your commitment matters.",
        "Every day counts.",
        "Quiet progress is still progress.",
        "You're rewriting your story.",
        "Just one more good day.",
        "The best time to check in is now.",
        "You're building something real.",
        "Small wins stack up.",
        "Trust the process.",
        "You're making a real difference.",
        "Keep your streak alive today.",
        "You're choosing better every day.",
        "Gentle reminder: you're doing amazing.",
        "Stay the course.",
        "You don't have to be perfect — just present.",
        "Today matters more than you think.",
        "Your streak is proof of your strength.",
        "Believe in your progress.",
        "You're not starting over — you're continuing.",
        "This gets easier with time.",
        "You've already started the hardest part.",
        "One more day of being good to yourself.",
        "You're capable of incredible things.",
        "Let today be another good one.",
        "Check in — it takes just a second.",
        "You're on the right path.",
        "Don't break the chain.",
        "Your discipline is inspiring.",
        "Take a breath. You're doing well.",
        "You deserve this progress.",
        "Stay calm and stay on track.",
        "You've handled harder days than this.",
        "Progress, not perfection.",
        "You're investing in yourself.",
        "Today is a gift to your future.",
        "You're more resilient than you know.",
        "Keep stacking those good days.",
        "A quick check-in goes a long way.",
        "You're in control.",
        "Celebrate how far you've come.",
        "This is your journey — own it.",
        "Momentum is on your side.",
        "You're showing real dedication.",
        "One day closer to your goal.",
        "Stay focused. Stay kind to yourself.",
        "You're building a new normal.",
        "The streak doesn't build itself — you do.",
        "Be proud of today.",
        "You're choosing yourself today.",
        "Slow and steady wins.",
        "Another chance to be great.",
        "Your effort is never wasted.",
        "You're already ahead of where you were.",
        "Keep it simple. Keep going.",
        "You matter. Your progress matters.",
        "Tap in and keep moving forward.",
        "You've earned this momentum.",
        "Today's effort is tomorrow's reward.",
        "The hardest part is behind you.",
        "You're quietly becoming unstoppable.",
        "Stay patient with yourself.",
        "Consistency beats intensity.",
        "You're doing this for the right reasons.",
        "Small actions create lasting change.",
        "You're showing up for yourself.",
        "This is what courage looks like.",
        "Keep your eyes forward.",
        "You're breaking old patterns.",
        "A calm mind makes better choices.",
        "You're already winning.",
        "Don't underestimate your progress.",
        "One good choice at a time.",
        "You've got more strength than you realize.",
        "Let this be a good day.",
        "You're not alone in this.",
        "Steady progress is real progress.",
        "You're creating positive change.",
        "Stay gentle with yourself today.",
        "Your streak speaks for itself.",
        "You're doing something meaningful.",
        "Each day you choose better.",
        "You're transforming your habits.",
        "Take it one moment at a time.",
        "You've been consistent — keep it going.",
        "Your daily effort adds up.",
        "You're building inner strength.",
        "The path forward is one step away.",
        "You're becoming who you want to be.",
        "Stay present. Stay committed.",
        "Today is full of possibility.",
        "You're writing a better chapter.",
        "Give yourself credit for showing up.",
        "You're doing better than you feel.",
        "Keep the faith in your progress.",
        "One tap. One win. That's all it takes.",
        "You've got a good thing going.",
        "Your willpower is growing every day.",
        "Stay connected to your why.",
        "You're proving doubts wrong.",
        "Another day of choosing yourself.",
        "Your consistency is remarkable.",
        "Let today count.",
        "You've built something to be proud of.",
        "Keep nurturing your progress.",
        "You're on a roll — don't stop now.",
        "Breathe in. You're doing this.",
        "The best version of you is showing up.",
        "You're stronger with each passing day.",
        "Stay grounded. Stay motivated.",
        "You're making space for better things.",
        "This moment is yours.",
        "You're putting in the work quietly.",
        "Good habits grow with patience.",
        "You're in a better place than last week.",
        "Stay with it — greatness takes time.",
        "You're not just surviving, you're thriving.",
        "Let your progress motivate you.",
        "You're doing something most people can't.",
        "Embrace the day ahead.",
        "Your dedication is paying off.",
        "You've got this — one more day.",
        "You're leaving old habits behind.",
        "Keep building, keep growing.",
        "You're more determined than you know.",
        "Be kind to yourself today.",
        "Another step in the right direction.",
        "You're creating a life you're proud of.",
        "Focus on today — that's enough.",
        "You're turning intentions into actions.",
        "Stay calm and carry on.",
        "Your progress is yours to keep.",
        "You're choosing health over habit.",
        "Let today be a statement.",
        "You're defying expectations.",
        "Keep the momentum rolling.",
        "You're growing through what you go through.",
        "Patience and persistence — you've got both.",
        "You're doing the right thing.",
        "Show up today like you mean it.",
        "You're one step ahead of yesterday.",
        "Let your streak inspire you.",
        "You're putting yourself first.",
        "Stay the path — it's working.",
        "Your effort today creates tomorrow's freedom.",
        "You're healing, day by day.",
        "Keep choosing progress.",
        "You're braver than you believe.",
        "Today is another opportunity.",
        "You're laying a strong foundation.",
        "Stay curious about your own growth.",
        "You're exactly where you need to be.",
        "Keep it going — you'll be glad you did.",
        "You're making progress without even trying.",
        "Let go of yesterday. Focus on today.",
        "You're in the middle of something great.",
        "You've got more grit than you realize.",
        "Quiet persistence changes everything.",
        "You're reclaiming your time and money.",
        "One more day of saying yes to yourself.",
        "You're moving forward, even when it's hard.",
        "Keep planting seeds of change.",
        "You're proof that change is possible.",
        "Stay in the moment. You're doing well.",
        "Your habits are shifting in the right direction.",
        "You're choosing clarity over chaos.",
        "Let yourself feel proud today.",
        "You're carving out a new path.",
        "One day is all you need to focus on.",
        "You're stronger than any craving.",
        "Stay anchored to your goals.",
        "You're making peace with the process.",
        "Each check-in is a small victory.",
        "You're committed, and it shows.",
        "Keep that fire burning quietly.",
        "You're gaining ground every day.",
        "Today is a fresh start.",
        "You're handling this with grace.",
        "Stay encouraged — the numbers don't lie.",
        "You're building resilience one day at a time.",
        "Give yourself permission to feel good.",
        "You're getting closer to your goals.",
        "A little effort today goes a long way.",
        "You're rising above old patterns.",
        "Stay soft with yourself. Stay strong in purpose.",
        "You're saving more than just money.",
        "Let your actions speak today.",
        "You're creating new defaults.",
        "Keep trusting yourself.",
        "You're worth every ounce of effort.",
        "Stay hopeful. Stay focused.",
        "You're changing the game.",
        "Today is a great day to continue.",
        "You're living proof of progress.",
        "Let this be a day you're proud of.",
        "You're building freedom, one day at a time.",
        "Stay disciplined and compassionate.",
        "You're not going back — only forward.",
        "Keep your head up. You're winning.",
        "You're taking control of your story.",
        "Let today add to your momentum.",
        "You're the architect of your change.",
        "Stay true to your commitment.",
        "You're trading habits for hope.",
        "One more peaceful day ahead.",
        "You're doing this with real intention.",
        "Keep showing up. That's the secret.",
        "You're making waves with small steps.",
        "Today's a good day to keep going.",
        "You're cultivating a better life.",
        "Stay in your lane. Stay consistent.",
        "You've earned every day of progress.",
        "Let your calm be your power.",
        "You're replacing old urges with new strength.",
        "Stay rooted in your decision.",
        "You're gaining more than you're giving up.",
        "One moment of strength starts here.",
        "You're shaping something lasting.",
        "Keep going — the view gets better.",
        "You're reclaiming peace of mind.",
        "Today is yours to own.",
        "You're living with more intention now.",
        "Stay steady. The results are coming.",
        "You're turning discipline into freedom.",
        "Let today's check-in be a celebration.",
        "You're doing what matters most.",
        "Keep believing in what you've started.",
        "You're closer than you were yesterday.",
        "Stay focused on what you can control.",
        "You're letting go of what held you back.",
        "One good day is all it takes.",
        "You're becoming more yourself every day.",
        "Stay proud of every small step.",
        "You're outgrowing old versions of yourself.",
        "Let progress fuel your confidence.",
        "You're building a habit of strength.",
        "Today's win is waiting for you.",
        "You're choosing a better path.",
        "Stay light. Stay focused. Stay you.",
        "You're turning effort into results.",
        "Keep writing your comeback story.",
        "You're doing this — and it's working.",
        "Let today be easy and intentional.",
        "You're defining your own success.",
        "Stay connected to your progress.",
        "You're making it look effortless.",
        "One more day of being unstoppable.",
        "You're the calm in your own storm.",
        "Keep honoring your commitment.",
        "You're waking up stronger every day.",
        "Today's choice shapes tomorrow's story.",
        "You're already miles ahead.",
        "Stay present. Stay powerful.",
        "You're mastering the art of showing up.",
        "Let this moment remind you of your strength.",
        "You're creating a ripple of positive change.",
        "Keep going — even the smallest steps count.",
        "You're learning to trust yourself again.",
        "Stay inspired by your own journey.",
        "You're not counting days — you're making them count.",
    ]
}
